##
# Set up a local Learning Locker instance
#

---
- hosts: default
  user: root

  vars_files:
    - vars.global.yml
    - vars.project.yml
    - vars.secret.yml

  tasks:
    ##
    # Set Hostname
    #
    - hostname: name={{ server_hostname }}

    ##
    # Message of the day explaining server is under control of Ansible.
    #
    - name: General | Setting message of the day.
      template:
        src=templates/motd.j2
        dest=/etc/update-motd.d/95-ansible
        mode=755

    ##
    # Apt package installation of required software.
    #
    - name: Packages | Set up required PPAs
      apt_repository: repo={{ item }}
      with_items: "{{ ppas }}"

    - name: Packages | Get mongo keys
      apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

    - name: Packages | Set the mongo repo
      apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'

    - name: Packages | Install required packages
      apt: pkg={{ item }} state=installed  update_cache=yes
      with_items: "{{ packages }}"

    - name: Packages | Upgrade
      apt: upgrade=yes autoremove=yes

    ##
    # Install composer
    #
    - name: Composer | Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Composer | Install composer
      shell: php5.6 /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer

    ##
    # Configure Postfix
    #
    - name: Postfix | Configure postfix server
      template:
        src=templates/etc-postfix-main-cf.j2
        dest=/etc/postfix/main.cf

    ##
    # Add user to mongo
    #
    - name: Mongo | Create user creation JS
      template:
        src=templates/home-vagrant-mongo-user-js.j2
        dest=/home/vagrant/mongo-user.js

    - name: Mongo | Create mongo user
      command: /usr/bin/mongo /home/vagrant/mongo-user.js

    ##
    # Restart services
    #
    - name: Restart nginx
      service:
        name=nginx
        state=started

    ##
    # Fix nodejs alias
    #
    - name: NodeJS | Fix a nodejs alias issue
      file:
        src=/usr/bin/nodejs
        dest=/usr/bin/node
        state=link

    ##
    # Install bower
    #
    - name: Bower | Install bower
      npm:
        name=bower
        global=yes

    ##
    # Install learninglocker
    #
    - name: LearningLocker | Set up Github OAuth key
      command: composer config -g github-oauth.github.com {{ github_token }}
      when: github_token != "false"

    - name: LearningLocker | Install Learning Locker
      command: composer create-project learninglocker/learninglocker learninglocker "{{ learninglocker_version }}" chdir=/var/www/

    - name: LearningLocker | Set the storage to writable
      file:
        owner=www-data
        group=www-data
        state=directory
        recurse=yes
        path=/var/www/learninglocker/app/storage

    - name: LearningLocker | Set app configuration
      template:
        src=templates/var-www-learninglocker-app-config-app-php.j2
        dest=/var/www/learninglocker/app/config/app.php

    - name: LearningLocker | Set database configuration
      template:
        src=templates/var-www-learninglocker-app-config-database-php.j2
        dest=/var/www/learninglocker/app/config/database.php

    - name: LearningLocker | Set mail configuration
      template:
        src=templates/var-www-learninglocker-app-config-mail-php.j2
        dest=/var/www/learninglocker/app/config/mail.php

    - name: LearningLocker | migrate
      command: php5.6 artisan migrate chdir=/var/www/learninglocker

    ##
    # nginx setup
    #
    - name: nginx | Configuration file for our site
      template:
        src=templates/etc-nginx-sites-available-default.j2
        dest=/etc/nginx/sites-available/default
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: >
        name=nginx
        state=restarted
